version: '3.8'
services:
  shoppingify:
    image: shoppingify
    build:
      context: .
      dockerfile: shoppingify/Dockerfile
  db: 
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoppingify
    ports:
        - "5432:5432"
  test_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoppingify_test
    ports:
        - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
        - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
    pgadmin: